// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button/index.vue')['default']
    ChainList: typeof import('./src/components/ChainList/index.vue')['default']
    CopyDialog: typeof import('./src/components/CopyDialog/index.vue')['default']
    CopyWrapper: typeof import('./src/components/CopyWrapper/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Header: typeof import('./src/components/Header/index.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    Textarea: typeof import('./src/components/Textarea/index.vue')['default']
  }
}

export { }
